language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
  # folder with Cypress binary
  - ~/.cache
after_success:
  - npm install -g firebase-tools
  - firebase use travis-testing
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
addons:
  apt:
    packages:
      # needed by Cypress, not in Ubuntu 16+ by default
      - libgconf-2-4
script:
  - npm run test:ci
  - npm run build